//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SitiosWebEntities1 : DbContext
    {
        public SitiosWebEntities1()
            : base("name=SitiosWebEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<EvidenciasPorDia> EvidenciasPorDia { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SolicitudHoras> SolicitudHoras { get; set; }
        public virtual DbSet<SolicitudPersonal> SolicitudPersonal { get; set; }
        public virtual DbSet<Tareas> Tareas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<string> ListaJefes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ListaJefes");
        }
    
        public virtual int SP_CrearSolicitudDeAumentoDePersonal_EmpleadoAJefe(Nullable<int> cedula_Solicitante, Nullable<int> cantidadDePersonas, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal, Nullable<int> iD_Tarea)
        {
            var cedula_SolicitanteParameter = cedula_Solicitante.HasValue ?
                new ObjectParameter("Cedula_Solicitante", cedula_Solicitante) :
                new ObjectParameter("Cedula_Solicitante", typeof(int));
    
            var cantidadDePersonasParameter = cantidadDePersonas.HasValue ?
                new ObjectParameter("CantidadDePersonas", cantidadDePersonas) :
                new ObjectParameter("CantidadDePersonas", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            var iD_TareaParameter = iD_Tarea.HasValue ?
                new ObjectParameter("ID_Tarea", iD_Tarea) :
                new ObjectParameter("ID_Tarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CrearSolicitudDeAumentoDePersonal_EmpleadoAJefe", cedula_SolicitanteParameter, cantidadDePersonasParameter, fechaInicioParameter, fechaFinalParameter, iD_TareaParameter);
        }
    
        public virtual int SP_CrearSolicitudDeHorasExtra_EmpleadoAJefe(Nullable<int> cedula_Solicitante, Nullable<int> horas, Nullable<int> iD_Tarea)
        {
            var cedula_SolicitanteParameter = cedula_Solicitante.HasValue ?
                new ObjectParameter("Cedula_Solicitante", cedula_Solicitante) :
                new ObjectParameter("Cedula_Solicitante", typeof(int));
    
            var horasParameter = horas.HasValue ?
                new ObjectParameter("Horas", horas) :
                new ObjectParameter("Horas", typeof(int));
    
            var iD_TareaParameter = iD_Tarea.HasValue ?
                new ObjectParameter("ID_Tarea", iD_Tarea) :
                new ObjectParameter("ID_Tarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CrearSolicitudDeHorasExtra_EmpleadoAJefe", cedula_SolicitanteParameter, horasParameter, iD_TareaParameter);
        }
    }
}
