//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvidenciasPorDia
    {
        public int ID_Evidencia { get; set; }
        public Nullable<int> Identificacion { get; set; }
        public Nullable<int> ID_Tarea { get; set; }
        public string FechaEvidencia { get; set; }
        public string Mensaje { get; set; }
    
        public virtual Tareas Tareas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
